# This zshrc will be source from /root/.zshrc upon launch of every terminal
# in a devcontainer that uses the bash-config feature from
# https://github.com/DiamondLightSource/devcontainer-features

# This file is initialized by vscode feature bash-config,
# but you are then free to edit it

# set up eternal history for zsh
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=10000000
SAVEHIST=$HISTSIZE
HISTFILE=$CONFIG_FOLDER/.zsh_eternal_history

# set a theme compatible with vscode terminals
ZSH_THEME="dst"
