name: CI

on:
  push:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  validate:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_validate.yml

  test:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_test.yml

  release:
    if: github.ref_type == 'tag'
    needs: test
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
      packages: write

